spring:
  application:
    name: car-reservation-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true

server:
  port: 9794

---
spring:
  config:
    activate:
      on-profile: localhost 
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public
  datasource:
    url: "jdbc:postgresql://localhost:5432/pandora"
    username: ozkan
    password: Asdf@1234
  data:
    redis:
      host: localhost
      port: 6379    

---
spring:
  config:
    activate:
      on-profile: stage
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_shema: public
  datasource:
    url: "jdbc:postgresql://postgres:5432/pandora"
    username: ozkan
    password: Asdf@1234  

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}